// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7FF9fNII1hm846Nu0qma2d9aK2EY8gs',
    appId: '1:75854224124:web:67e9b2882a758d9d6f1579',
    messagingSenderId: '75854224124',
    projectId: 'litestore-e5fac',
    authDomain: 'litestore-e5fac.firebaseapp.com',
    storageBucket: 'litestore-e5fac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_P2vVaCr5UzF8TV434ztCjFB3KeA8uo',
    appId: '1:75854224124:android:1b20fc64714869156f1579',
    messagingSenderId: '75854224124',
    projectId: 'litestore-e5fac',
    storageBucket: 'litestore-e5fac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqL1URSqQ0PITTHOPF_dEjqkzMUKHZlE',
    appId: '1:75854224124:ios:d0044a163b5bb2696f1579',
    messagingSenderId: '75854224124',
    projectId: 'litestore-e5fac',
    storageBucket: 'litestore-e5fac.appspot.com',
    iosBundleId: 'com.example.liteStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfqL1URSqQ0PITTHOPF_dEjqkzMUKHZlE',
    appId: '1:75854224124:ios:79aec4090f4189456f1579',
    messagingSenderId: '75854224124',
    projectId: 'litestore-e5fac',
    storageBucket: 'litestore-e5fac.appspot.com',
    iosBundleId: 'com.example.liteStore.RunnerTests',
  );
}
